version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: MSCOF-DB
    restart: always
    ports:
      - "9596:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MSCOF-DB
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 
volumes:
  postgres-data:
 